#NODE_ENV=development DATABASE_SERVER=localhost DATABASE_PORT=27017 DATABASE_USER=madalozzo DATABASE_PASSWORD=C0nnect123 DATABASE_NAME=pluviam nodemon pluviam.js
NODE_ENV=development DATABASE_SERVER=10.8.0.1 DATABASE_PORT=27017 DATABASE_USER=saulo DATABASE_PASSWORD=C0nnect123 DATABASE_NAME=pluviam nodemon pluviam.js
